version: '3.8'

services:
  # Streamlit frontend service
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped

  # CLI backend service (for testing)
  cli:
    build: .
    volumes:
      - .:/app
    command: tail -f /dev/null  # Keep container running for CLI access
    restart: unless-stopped 