# Phase 1 Configuration for Price Intelligence Platform
# Controls mock vs real implementations for each module

mode: mock
modules:
  query_normalizer:
    use_mock: true
    mock_output:
      brand: "Apple"
      model: "iPhone 16 Pro"
      storage: "128GB"
      category: "Smartphone"
    mock_data_path: "mocks/normalized_queries.yaml"
    
  site_selector:
    use_mock: true
    sites_by_country:
      US:
        - amazon.com
        - bestbuy.com
        - apple.com
      IN:
        - amazon.in
        - flipkart.com
        - croma.com
        - reliancedigital.in
        - paytmmall.com
        - snapdeal.com
        - shopclues.com
        - indiamart.com
      UK:
        - amazon.co.uk
        - currys.co.uk
        - argos.co.uk
      DE:
        - amazon.de
        - mediamarkt.de
        - saturn.de
    mock_data_path: "mocks/selected_sites.yaml"
    
  search_agent:
    use_mock: true
    mock_results:
      amazon.com:
        - url: https://amazon.com/iphone16pro
          html_file: mocks/html/amazon_iphone16pro.html
      bestbuy.com:
        - url: https://bestbuy.com/iphone16pro
          html_file: mocks/html/bestbuy_iphone16pro.html
      apple.com:
        - url: https://apple.com/iphone16pro
          html_file: mocks/html/apple_iphone16pro.html
      flipkart.com:
        - url: https://flipkart.com/iphone16pro
          html_file: mocks/html/flipkart_iphone16pro.html
      croma.com:
        - url: https://croma.com/iphone16pro
          html_file: mocks/html/croma_iphone16pro.html
      reliancedigital.in:
        - url: https://reliancedigital.in/iphone16pro
          html_file: mocks/html/reliancedigital_iphone16pro.html
      amazon.in:
        - url: https://amazon.in/iphone16pro
          html_file: mocks/html/amazon_in_iphone16pro.html
      paytmmall.com:
        - url: https://paytmmall.com/iphone16pro
          html_file: mocks/html/paytmmall_iphone16pro.html
      snapdeal.com:
        - url: https://snapdeal.com/iphone16pro
          html_file: mocks/html/snapdeal_iphone16pro.html
      shopclues.com:
        - url: https://shopclues.com/iphone16pro
          html_file: mocks/html/shopclues_iphone16pro.html
      indiamart.com:
        - url: https://indiamart.com/iphone16pro
          html_file: mocks/html/indiamart_iphone16pro.html
    mock_data_path: "mocks/search_results.yaml"
    
  scraper:
    use_mock: true
    mock_data_path: "mocks/html/"
    
  extractor:
    use_mock: true
    mock_extracts:
      https://amazon.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "999"
        currency: "USD"
        link: "https://amazon.com/iphone16pro"
      https://bestbuy.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB - Silver"
        price: "979"
        currency: "USD"
        link: "https://bestbuy.com/iphone16pro"
      https://apple.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB - Natural Titanium"
        price: "999"
        currency: "USD"
        link: "https://apple.com/iphone16pro"
      https://flipkart.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://flipkart.com/iphone16pro"
      https://croma.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://croma.com/iphone16pro"
      https://reliancedigital.in/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://reliancedigital.in/iphone16pro"
      https://amazon.in/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://amazon.in/iphone16pro"
      https://paytmmall.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://paytmmall.com/iphone16pro"
      https://snapdeal.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://snapdeal.com/iphone16pro"
      https://shopclues.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://shopclues.com/iphone16pro"
      https://indiamart.com/iphone16pro:
        productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://indiamart.com/iphone16pro"
    mock_data_path: "mocks/extracts/"
    
  validator:
    use_mock: true
    mock_validations:
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://amazon.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB - Silver"
          price: "979"
          currency: "USD"
          link: "https://bestbuy.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Mini"
          price: "899"
          currency: "USD"
          link: "https://example.com/iphone16mini"
        is_valid: false
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Samsung Galaxy S24"
          price: "999"
          currency: "USD"
          link: "https://example.com/galaxys24"
        is_valid: false
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 256GB"
          price: "1099"
          currency: "USD"
          link: "https://example.com/iphone16pro256"
        is_valid: false
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://flipkart.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://croma.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://reliancedigital.in/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://paytmmall.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://snapdeal.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://shopclues.com/iphone16pro"
        is_valid: true
      - query:
          brand: "Apple"
          model: "iPhone 16 Pro"
          storage: "128GB"
          category: "Smartphone"
        product:
          productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://indiamart.com/iphone16pro"
        is_valid: true
    mock_data_path: "mocks/validated_data.yaml"
    
  deduplicator:
    use_mock: true
    mock_deduplicated_results:
      input_products:
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://amazon.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Silver"
          price: "999"
          currency: "USD"
          link: "https://bestbuy.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Natural Titanium"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://flipkart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://croma.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://reliancedigital.in/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://paytmmall.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://snapdeal.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://shopclues.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://indiamart.com/iphone16pro"
      output_products:
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://amazon.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Silver"
          price: "999"
          currency: "USD"
          link: "https://bestbuy.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Natural Titanium"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://flipkart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://croma.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://reliancedigital.in/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://paytmmall.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://snapdeal.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://shopclues.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://indiamart.com/iphone16pro"
    mock_data_path: "mocks/deduplicated_data.yaml"
    
  ranker:
    use_mock: true
    mock_ranked_results:
      input_products:
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Silver"
          price: "979"
          currency: "USD"
          link: "https://bestbuy.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Natural Titanium"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Space Black"
          price: "1049"
          currency: "USD"
          link: "https://walmart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://flipkart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://croma.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://reliancedigital.in/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://paytmmall.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://snapdeal.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://shopclues.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://indiamart.com/iphone16pro"
      output_products:
        - productName: "Apple iPhone 16 Pro 128GB - Silver"
          price: "979"
          currency: "USD"
          link: "https://bestbuy.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Natural Titanium"
          price: "999"
          currency: "USD"
          link: "https://apple.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB - Space Black"
          price: "1049"
          currency: "USD"
          link: "https://walmart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://flipkart.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://croma.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://reliancedigital.in/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://paytmmall.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://snapdeal.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://shopclues.com/iphone16pro"
        - productName: "Apple iPhone 16 Pro 128GB"
          price: "89999"
          currency: "INR"
          link: "https://indiamart.com/iphone16pro"
    mock_data_path: "mocks/ranked_results.yaml"
    
  orchestrator:
    use_mock: false  # Orchestrator always uses real logic
    mock_product_list:
      - productName: "Apple iPhone 16 Pro 128GB"
        price: "999"
        currency: "USD"
        link: "https://apple.com/iphone16pro"
      - productName: "Apple iPhone 16 Pro 128GB Silver"
        price: "979"
        currency: "USD"
        link: "https://bestbuy.com/iphone16pro"
      - productName: "Apple iPhone 16 Pro 128GB Space Black"
        price: "1049"
        currency: "USD"
        link: "https://walmart.com/iphone16pro"
      - productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://flipkart.com/iphone16pro"
      - productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://croma.com/iphone16pro"
      - productName: "Apple iPhone 16 Pro 128GB"
        price: "89999"
        currency: "INR"
        link: "https://reliancedigital.in/iphone16pro"

# Global settings
settings:
  max_results: 10
  timeout_seconds: 30
  retry_attempts: 3
  
# Supported countries and their configurations
countries:
  US:
    currency: "USD"
    language: "en"
    sites: ["amazon.com", "bestbuy.com", "walmart.com"]
  UK:
    currency: "GBP"
    language: "en"
    sites: ["amazon.co.uk", "currys.co.uk", "argos.co.uk"]
  DE:
    currency: "EUR"
    language: "de"
    sites: ["amazon.de", "mediamarkt.de", "saturn.de"]
  IN:
    currency: "INR"
    language: "en"
    sites: ["amazon.in", "flipkart.com", "croma.com", "reliancedigital.in", "paytmmall.com", "snapdeal.com", "shopclues.com", "indiamart.com"]
    timezone: "Asia/Kolkata"
    locale: "en_IN" 